# Generated by Django 5.1 on 2024-08-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='position',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
    ]
