# Generated by Django 4.2.4 on 2024-08-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('outsource', 'Outsource'), ('outstaff', 'Outstaff'), ('product', 'Product'), ('startup', 'Startup')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_type',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('outsource', 'Outsource'), ('outstaff', 'Outstaff'), ('product', 'Product'), ('startup', 'Startup')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('0', 'No experience'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('5', '5 years')], default='', max_length=10, null=True),
        ),
    ]
