# Generated by Django 4.2.4 on 2024-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('outsource', 'Outsource'), ('outstaff', 'Outstaff'), ('product', 'Product'), ('startup', 'Startup')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_type',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('outsource', 'Outsource'), ('outstaff', 'Outstaff'), ('product', 'Product'), ('startup', 'Startup')], default='', max_length=20, null=True),
        ),
    ]
