# Generated by Django 4.2.4 on 2024-08-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20240806_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('outsource', 'Outsource'), ('outstaff', 'Outstaff'), ('product', 'Product'), ('startup', 'Startup')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_type',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('outsource', 'Outsource'), ('outstaff', 'Outstaff'), ('product', 'Product'), ('startup', 'Startup')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='remote_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('partly_remote', 'Hybrid'), ('full_remote', 'Remote'), ('candidate_choice', 'Office/Remote of your choice')], default='', max_length=20, null=True),
        ),
    ]
