# Generated by Django 5.1 on 2024-08-09 18:09

from django.db import migrations
from django.contrib.postgres.search import SearchVector


def update_vectors(apps, schema_editor):
    JobPosting = apps.get_model('jobs', 'JobPosting')
    vector = SearchVector('position', weight='A') + \
        SearchVector('long_description', weight='B') + \
        SearchVector('primary_keyword', weight='A') + \
        SearchVector('secondary_keyword', weight='B') + \
        SearchVector('extra_keywords', weight='C')
    JobPosting.objects.update(search_vector=SearchVector(vector))


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_search_vector_and_more'),
    ]

    operations = [
        migrations.RunPython(update_vectors),
    ]
